/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./App.tsx', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        // ---- Light theme (Onboarding, Inicio, Filtros, Historial, Voz) ----
        'on-surface': '#131b2e',
        'primary-fixed': '#d6e3ff',
        secondary: '#5c5f61',
        background: '#faf8ff',
        'on-tertiary-fixed': '#161c22',
        'on-tertiary': '#ffffff',
        'secondary-fixed-dim': '#c4c7c9',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#1a365d',
        'on-tertiary-fixed-variant': '#41474e',
        'on-secondary-container': '#626567',
        'tertiary-fixed': '#dde3eb',
        'on-primary-container': '#86a0cd',
        'inverse-primary': '#adc7f7',
        primary: '#002045',
        error: '#ba1a1a',
        'surface-container-high': '#e2e7ff',
        'on-error-container': '#93000a',
        'surface-bright': '#faf8ff',
        'on-secondary-fixed': '#191c1e',
        'on-primary': '#ffffff',
        'on-surface-variant': '#43474e',
        'on-tertiary-container': '#989fa6',
        'on-secondary': '#ffffff',
        'surface-container': '#eaedff',
        'surface-variant': '#dae2fd',
        'error-container': '#ffdad6',
        'tertiary-container': '#30363c',
        'on-error': '#ffffff',
        'on-background': '#131b2e',
        'outline-variant': '#c4c6cf',
        'secondary-fixed': '#e0e3e5',
        'surface-tint': '#455f88',
        'tertiary-fixed-dim': '#c1c7cf',
        surface: '#faf8ff',
        outline: '#74777f',
        'surface-container-highest': '#dae2fd',
        'on-primary-fixed-variant': '#2d476f',
        'inverse-on-surface': '#eef0ff',
        'on-primary-fixed': '#001b3c',
        'on-secondary-fixed-variant': '#444749',
        'surface-container-low': '#f2f3ff',
        'primary-fixed-dim': '#adc7f7',
        'inverse-surface': '#283044',
        'secondary-container': '#e0e3e5',
        'surface-dim': '#d2d9f4',
        tertiary: '#1b2127',

        // ---- Train (Entrenar) fixed-dark theme — deliberately distinct palette ----
        'train-secondary-fixed-dim': '#2edcd7',
        'train-on-secondary-fixed-variant': '#00504e',
        'train-on-error': '#690005',
        'train-primary': '#c6bfff',
        'train-inverse-primary': '#5847d2',
        'train-on-tertiary-fixed': '#360f06',
        'train-surface-container-highest': '#2f3638',
        'train-on-surface': '#dde4e6',
        'train-surface-bright': '#333a3c',
        'train-inverse-surface': '#dde4e6',
        'train-tertiary-fixed-dim': '#feb5a4',
        'train-surface-variant': '#2f3638',
        'train-surface-container-low': '#161d1f',
        'train-surface-container': '#1a2123',
        'train-surface': '#0e1416',
        'train-on-tertiary': '#502318',
        'train-on-tertiary-container': '#fff6f4',
        'train-surface-container-high': '#242b2d',
        'train-on-secondary-fixed': '#00201f',
        'train-on-secondary-container': '#005250',
        'train-outline-variant': '#474554',
        'train-surface-dim': '#0e1416',
        'train-error-container': '#93000a',
        'train-secondary-container': '#00cec9',
        'train-on-secondary': '#003735',
        'train-on-primary-fixed-variant': '#4029ba',
        'train-surface-container-lowest': '#080f11',
        'train-on-surface-variant': '#c8c4d7',
        'train-surface-tint': '#c6bfff',
        'train-background': '#0e1416',
        'train-secondary': '#46eae5',
        'train-tertiary-fixed': '#ffdad2',
        'train-on-primary': '#2900a0',
        'train-tertiary': '#feb5a4',
        'train-on-error-container': '#ffdad6',
        'train-inverse-on-surface': '#2b3234',
        'train-secondary-fixed': '#5af9f3',
        'train-on-background': '#dde4e6',
        'train-on-primary-fixed': '#160066',
        'train-on-primary-container': '#faf6ff',
        'train-on-tertiary-fixed-variant': '#6c392c',
        'train-primary-fixed': '#e4dfff',
        'train-outline': '#928ea0',
        'train-tertiary-container': '#9e6254',
        'train-error': '#ffb4ab',
        'train-primary-fixed-dim': '#c6bfff',
        'train-primary-container': '#6c5ce7',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
        train: '0.125rem',
        'train-lg': '0.25rem',
        'train-xl': '0.5rem',
        'train-full': '0.75rem',
      },
      spacing: {
        base: '4px',
        'touch-target-min': '48px',
        lg: '24px',
        xs: '8px',
        'gutter-mobile': '12px',
        'margin-mobile': '20px',
        xl: '32px',
        md: '16px',
        sm: '12px',
        // Train scale
        'train-gutter': '24px',
        'train-unit': '8px',
        'train-margin-mobile': '16px',
        'train-stack-sm': '8px',
        'train-stack-md': '16px',
        'train-stack-lg': '32px',
        'train-margin-desktop': '40px',
        'train-container-max': '1280px',
      },
      fontFamily: {
        'body-md': ['AtkinsonHyperlegibleNext_400Regular'],
        'headline-lg': ['PlusJakartaSans_600SemiBold'],
        'headline-md': ['PlusJakartaSans_600SemiBold'],
        display: ['PlusJakartaSans_700Bold'],
        'label-lg': ['AtkinsonHyperlegibleNext_700Bold'],
        'label-md': ['AtkinsonHyperlegibleNext_600SemiBold'],
        'body-lg': ['AtkinsonHyperlegibleNext_400Regular'],
        // Train scale (all Plus Jakarta Sans)
        'train-body-lg': ['PlusJakartaSans_400Regular'],
        'train-display-lg': ['PlusJakartaSans_700Bold'],
        'train-title-md': ['PlusJakartaSans_600SemiBold'],
        'train-body-sm': ['PlusJakartaSans_400Regular'],
        'train-label-caps': ['PlusJakartaSans_700Bold'],
        'train-headline-lg-mobile': ['PlusJakartaSans_700Bold'],
        'train-headline-lg': ['PlusJakartaSans_700Bold'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg-mobile': ['22px', { lineHeight: '28px', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        display: ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        // Train scale
        'train-body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'train-display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'train-title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'train-body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'train-label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'train-headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'train-headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
